In [2]:
import pandas as pd

In [3]:
LAB_DATA_ORIGINAL = "/home/dungx/Workspace/VNU-UET/nam4/hk1/Big-Data-Techniques-And-Technologies/physionet.org/files/eicu-crd-demo/2.0.1/lab.csv"

In [4]:
lab_df = pd.read_csv(LAB_DATA_ORIGINAL)

In [5]:
print(lab_df["patientunitstayid"].nunique())
print(lab_df["patientunitstayid"].value_counts())

2444
patientunitstayid
521456     2727
1858620    2144
2416376    1702
2571798    1573
1101375    1308
           ...
3150353       1
346753        1
1790300       1
859202        1
2999209       1
Name: count, Length: 2444, dtype: int64

In [4]:
print(lab_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 434660 entries, 0 to 434659
Data columns (total 10 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   labid                    434660 non-null  int64
 1   patientunitstayid        434660 non-null  int64
 2   labresultoffset          434660 non-null  int64
 3   labtypeid                434660 non-null  int64
 4   labname                  434660 non-null  str
 5   labresult                431939 non-null  float64
 6   labresulttext            434639 non-null  str
 7   labmeasurenamesystem     415754 non-null  str
 8   labmeasurenameinterface  415763 non-null  str
 9   labresultrevisedoffset   434660 non-null  int64
dtypes: float64(1), int64(5), str(4)
memory usage: 41.0 MB
None

In [8]:
display(lab_df.head())

,labid,patientunitstayid,labresultoffset,labtypeid,labname,labresult,labresulttext,labmeasurenamesystem,labmeasurenameinterface,labresultrevisedoffset
0,437880563,1754323,-647,3,Hct,38.30,38.3,%,%,-631
1,437880572,1754323,-647,3,platelets x 1000,181.00,181,K/mcL,k/mm cu,-631
2,437880560,1754323,-647,3,RBC,4.86,4.86,M/mcL,m/mm cu,-631
3,437880570,1754323,-647,3,#NAME?,8.70,8.7,%,%,-631
4,437880571,1754323,-647,3,MCHC,30.40,30.4,g/dL,%,-631

In [12]:
print(lab_df.shape)

(434660, 10)

In [13]:
print(lab_df["labid"].nunique())

434660

In [11]:
print(lab_df["labid"].value_counts())

labid
437880563    1
437880572    1
437880560    1
437880570    1
437880571    1
            ..
672795149    1
641165125    1
667153606    1
673870691    1
634715053    1
Name: count, Length: 434660, dtype: int64

In [14]:
print(lab_df["labid"].min())
print(lab_df["labid"].max())

42641533
830006654

In [15]:
print(lab_df["labname"].nunique())

142

In [16]:
print(lab_df["labname"].value_counts())

labname
#NAME?                       39363
bedside glucose              29965
potassium                    16337
sodium                       15414
glucose                      14983
                             ...
WBC's in synovial fluid          1
HSV 1&2 IgG AB                   1
Mode                             1
Amikacin - peak                  1
WBC's in peritoneal fluid        1
Name: count, Length: 142, dtype: int64

In [23]:
display(lab_df[lab_df["labname"] == "#NAME?"])

,labid,patientunitstayid,labresultoffset,labtypeid,labname,labresult,labresulttext,labmeasurenamesystem,labmeasurenameinterface,labresultrevisedoffset
3,437880570,1754323,-647,3,#NAME?,8.7,8.7,%,%,-631
26,437880564,1754323,-647,3,#NAME?,1.2,1.2,%,%,-631
29,429757534,1754323,5073,3,#NAME?,18.6,18.6,%,%,5117
33,429757536,1754323,5073,3,#NAME?,1.4,1.4,%,%,5117
38,429757535,1754323,5073,3,#NAME?,7.4,7.4,%,%,5117
...,...,...,...,...,...,...,...,...,...,...
434475,654733782,2715137,3236,3,#NAME?,1.0,1,%,%,3258
434590,661063825,2754778,1282,3,#NAME?,2.0,2,%,%,1282
434603,661063826,2754778,1282,3,#NAME?,0.0,0,%,%,1282
434624,667153611,2754778,37,3,#NAME?,2.0,2,%,%,37
434630,667153612,2754778,37,3,#NAME?,0.0,0,%,%,37