In [2]:
import pandas as pd

In [3]:
# đường dẫn đến file patient.csv
PATIENT_DATA_ORIGINAL = "/home/dungx/Workspace/VNU-UET/nam4/hk1/Big-Data-Techniques-And-Technologies/physionet.org/files/eicu-crd-demo/2.0.1/patient.csv"
# PATIENT_DATA_ORIGINAL = "physionet.org/files/eicu-crd-demo/2.0.1/patient.csv"

In [4]:
patient_df = pd.read_csv(PATIENT_DATA_ORIGINAL)

In [5]:
print(patient_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 2520 entries, 0 to 2519
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   patientunitstayid          2520 non-null   int64
 1   patienthealthsystemstayid  2520 non-null   int64
 2   gender                     2516 non-null   str
 3   age                        2516 non-null   str
 4   ethnicity                  2481 non-null   str
 5   hospitalid                 2520 non-null   int64
 6   wardid                     2520 non-null   int64
 7   apacheadmissiondx          2221 non-null   str
 8   admissionheight            2451 non-null   float64
 9   hospitaladmittime24        2520 non-null   str
 10  hospitaladmitoffset        2520 non-null   int64
 11  hospitaladmitsource        1926 non-null   str
 12  hospitaldischargeyear      2520 non-null   int64
 13  hospitaldischargetime24    2520 non-null   str
 14  hospitaldischargeoffset    2520 non-null   int64
 15  hospitaldischargelocation  2488 non-null   str
 16  hospitaldischargestatus    2492 non-null   str
 17  unittype                   2520 non-null   str
 18  unitadmittime24            2520 non-null   str
 19  unitadmitsource            2498 non-null   str
 20  unitvisitnumber            2520 non-null   int64
 21  unitstaytype               2520 non-null   str
 22  admissionweight            2322 non-null   float64
 23  dischargeweight            1236 non-null   float64
 24  unitdischargetime24        2520 non-null   str
 25  unitdischargeoffset        2520 non-null   int64
 26  unitdischargelocation      2516 non-null   str
 27  unitdischargestatus        2518 non-null   str
 28  uniquepid                  2520 non-null   str
dtypes: float64(3), int64(9), str(17)
memory usage: 964.4 KB
None

In [6]:
print(patient_df.describe())

       patientunitstayid  patienthealthsystemstayid   hospitalid       wardid  \
count       2.520000e+03               2.520000e+03  2520.000000  2520.000000
mean        1.666226e+06               1.326635e+06   261.042460   629.305952
std         1.022224e+06               8.311521e+05   119.109829   318.083552
min         1.417640e+05               1.293910e+05    56.000000    82.000000
25%         7.722628e+05               5.938000e+05   158.000000   376.000000
50%         1.590372e+06               1.230992e+06   252.500000   626.000000
75%         2.697422e+06               2.165279e+06   384.500000   957.000000
max         3.353113e+06               2.742979e+06   459.000000  1111.000000

       admissionheight  hospitaladmitoffset  hospitaldischargeyear  \
count      2451.000000          2520.000000            2520.000000
mean        169.740445         -2017.725794            2014.522222
std          15.986092          7217.011876               0.499605
min           0.300000       -251404.000000            2014.000000
25%         162.600000         -1173.250000            2014.000000
50%         170.200000          -270.000000            2015.000000
75%         177.800000           -92.000000            2015.000000
max         600.000000          8696.000000            2015.000000

       hospitaldischargeoffset  unitvisitnumber  admissionweight  \
count              2520.000000      2520.000000      2322.000000
mean               8026.446429         1.200000        83.087795
std                9352.901755         0.510003        26.606384
min                  20.000000         1.000000         0.500000
25%                2606.500000         1.000000        65.500000
50%                5474.500000         1.000000        79.300000
75%                9996.750000         1.000000        96.600000
max              143016.000000         5.000000       515.000000

       dischargeweight  unitdischargeoffset
count      1236.000000          2520.000000
mean         83.051586          3484.075000
std          26.465304          4977.160994
min          22.300000             0.000000
25%          64.275000          1137.750000
50%          79.550000          2120.000000
75%          98.400000          3998.500000
max         242.000000         66499.000000

In [7]:
display(patient_df.describe())

,patientunitstayid,patienthealthsystemstayid,hospitalid,wardid,admissionheight,hospitaladmitoffset,hospitaldischargeyear,hospitaldischargeoffset,unitvisitnumber,admissionweight,dischargeweight,unitdischargeoffset
count,2.520000e+03,2.520000e+03,2520.000000,2520.000000,2451.000000,2520.000000,2520.000000,2520.000000,2520.000000,2322.000000,1236.000000,2520.000000
mean,1.666226e+06,1.326635e+06,261.042460,629.305952,169.740445,-2017.725794,2014.522222,8026.446429,1.200000,83.087795,83.051586,3484.075000
std,1.022224e+06,8.311521e+05,119.109829,318.083552,15.986092,7217.011876,0.499605,9352.901755,0.510003,26.606384,26.465304,4977.160994
min,1.417640e+05,1.293910e+05,56.000000,82.000000,0.300000,-251404.000000,2014.000000,20.000000,1.000000,0.500000,22.300000,0.000000
25%,7.722628e+05,5.938000e+05,158.000000,376.000000,162.600000,-1173.250000,2014.000000,2606.500000,1.000000,65.500000,64.275000,1137.750000
50%,1.590372e+06,1.230992e+06,252.500000,626.000000,170.200000,-270.000000,2015.000000,5474.500000,1.000000,79.300000,79.550000,2120.000000
75%,2.697422e+06,2.165279e+06,384.500000,957.000000,177.800000,-92.000000,2015.000000,9996.750000,1.000000,96.600000,98.400000,3998.500000
max,3.353113e+06,2.742979e+06,459.000000,1111.000000,600.000000,8696.000000,2015.000000,143016.000000,5.000000,515.000000,242.000000,66499.000000

In [8]:
display(patient_df.head())

,patientunitstayid,patienthealthsystemstayid,gender,age,ethnicity,hospitalid,wardid,apacheadmissiondx,admissionheight,hospitaladmittime24,...,unitadmitsource,unitvisitnumber,unitstaytype,admissionweight,dischargeweight,unitdischargetime24,unitdischargeoffset,unitdischargelocation,unitdischargestatus,uniquepid
0,141764,129391,Female,87,Caucasian,59,91,NaN,157.5,23:36:00,...,ICU to SDU,2,stepdown/other,NaN,NaN,18:58:00,344,Home,Alive,002-1039
1,141765,129391,Female,87,Caucasian,59,91,"Rhythm disturbance (atrial, supraventricular)",157.5,23:36:00,...,Emergency Department,1,admit,46.5,45.0,13:14:00,2250,Step-Down Unit (SDU),Alive,002-1039
2,143870,131022,Male,76,Caucasian,68,103,"Endarterectomy, carotid",167.0,20:46:00,...,Operating Room,1,admit,77.5,79.4,10:00:00,793,Floor,Alive,002-12289
3,144815,131736,Female,34,Caucasian,56,82,"Overdose, other toxin, poison or drug",172.7,1:44:00,...,Emergency Department,1,admit,60.3,60.7,20:48:00,1121,Other External,Alive,002-1116
4,145427,132209,Male,61,Caucasian,68,103,"GI perforation/rupture, surgery for",177.8,23:48:00,...,Operating Room,1,admit,91.7,93.1,22:47:00,1369,Floor,Alive,002-12243

In [9]:
print(patient_df["hospitalid"].unique()) # unique: Trả về danh sách các giá trị duy nhất.

[ 59  68  56  63  67  61  60  66  73  71  58  69 108  95  93  83  92  79
 123 133 110 131 112 115 120 125 122 138 141 142 140 143 144 175 176 179
 171 165 146 164 167 174 152 157 155 154 158 148 181 184 180 183 182 188
 194 196 195 197 198 201 205 206 199 200 204 203 202 210 208 209 207 215
 224 217 220 226 227 244 246 245 243 252 248 249 251 253 250 262 263 254
 264 258 256 259 266 267 269 282 272 279 275 268 281 280 283 271 273 277
 312 301 300 318 310 307 303 338 328 336 342 337 345 331 350 352 356 357
 365 358 363 364 360 353 355 390 404 389 405 388 382 387 407 408 398 393
 384 383 403 386 396 397 399 402 391 400 394 381 392 411 413 412 417 416
 425 421 420 424 423 422 419 439 429 434 437 428 440 436 438 435 433 443
 444 449 445 452 458 459]

In [10]:
print(patient_df["hospitalid"].nunique()) # nunique → Trả về số lượng giá trị duy nhất.

186

In [11]:
print(patient_df['hospitalid'].value_counts())

hospitalid
146    40
123    30
171    25
157    25
167    24
       ..
381    10
416    10
419    10
449    10
452    10
Name: count, Length: 186, dtype: int64

In [12]:
print(patient_df["hospitalid"].value_counts().head(5))

hospitalid
146    40
123    30
171    25
157    25
167    24
Name: count, dtype: int64

In [13]:
print(patient_df["hospitalid"].value_counts().index[0])

146

In [14]:
patient_hospital_A_df = patient_df[patient_df["hospitalid"] == patient_df["hospitalid"].value_counts().index[0]]
display(patient_hospital_A_df.head(5))

,patientunitstayid,patienthealthsystemstayid,gender,age,ethnicity,hospitalid,wardid,apacheadmissiondx,admissionheight,hospitaladmittime24,...,unitadmitsource,unitvisitnumber,unitstaytype,admissionweight,dischargeweight,unitdischargetime24,unitdischargeoffset,unitdischargelocation,unitdischargestatus,uniquepid
470,544158,456983,Male,29,Caucasian,146,374,NaN,170.0,5:24:00,...,ICU,2,stepdown/other,57.0,59.4,18:19:00,1402,Home,Alive,006-100497
471,544159,456983,Male,29,Caucasian,146,374,Diabetic ketoacidosis,170.0,5:24:00,...,Emergency Department,1,admit,57.0,55.7,18:57:00,639,Step-Down Unit (SDU),Alive,006-100497
479,562305,467859,Male,28,Caucasian,146,374,Diabetic ketoacidosis,170.0,2:34:00,...,Emergency Department,1,admit,56.8,56.8,3:14:00,1384,Home,Alive,006-100497
515,593654,486652,Male,63,Caucasian,146,374,NaN,178.0,15:33:00,...,Direct Admit,1,stepdown/other,101.6,NaN,21:15:00,1605,Home,Alive,006-101333
529,609949,496478,Female,48,Hispanic,146,374,"CVA, cerebrovascular accident/stroke",163.0,21:07:00,...,Floor,1,admit,65.9,NaN,2:00:00,261,Other Hospital,Alive,006-10232

In [15]:
display(patient_hospital_A_df.info())

<class 'pandas.DataFrame'>
Index: 40 entries, 470 to 773
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   patientunitstayid          40 non-null     int64
 1   patienthealthsystemstayid  40 non-null     int64
 2   gender                     40 non-null     str
 3   age                        40 non-null     str
 4   ethnicity                  40 non-null     str
 5   hospitalid                 40 non-null     int64
 6   wardid                     40 non-null     int64
 7   apacheadmissiondx          25 non-null     str
 8   admissionheight            40 non-null     float64
 9   hospitaladmittime24        40 non-null     str
 10  hospitaladmitoffset        40 non-null     int64
 11  hospitaladmitsource        34 non-null     str
 12  hospitaldischargeyear      40 non-null     int64
 13  hospitaldischargetime24    40 non-null     str
 14  hospitaldischargeoffset    40 non-null     int64
 15  hospitaldischargelocation  40 non-null     str
 16  hospitaldischargestatus    40 non-null     str
 17  unittype                   40 non-null     str
 18  unitadmittime24            40 non-null     str
 19  unitadmitsource            40 non-null     str
 20  unitvisitnumber            40 non-null     int64
 21  unitstaytype               40 non-null     str
 22  admissionweight            31 non-null     float64
 23  dischargeweight            25 non-null     float64
 24  unitdischargetime24        40 non-null     str
 25  unitdischargeoffset        40 non-null     int64
 26  unitdischargelocation      40 non-null     str
 27  unitdischargestatus        40 non-null     str
 28  uniquepid                  40 non-null     str
dtypes: float64(3), int64(9), str(17)
memory usage: 15.2 KB

None

In [16]:
print(patient_hospital_A_df.columns)

Index(['patientunitstayid', 'patienthealthsystemstayid', 'gender', 'age',
       'ethnicity', 'hospitalid', 'wardid', 'apacheadmissiondx',
       'admissionheight', 'hospitaladmittime24', 'hospitaladmitoffset',
       'hospitaladmitsource', 'hospitaldischargeyear',
       'hospitaldischargetime24', 'hospitaldischargeoffset',
       'hospitaldischargelocation', 'hospitaldischargestatus', 'unittype',
       'unitadmittime24', 'unitadmitsource', 'unitvisitnumber', 'unitstaytype',
       'admissionweight', 'dischargeweight', 'unitdischargetime24',
       'unitdischargeoffset', 'unitdischargelocation', 'unitdischargestatus',
       'uniquepid'],
      dtype='str')

In [17]:
print(patient_df.shape)
print(patient_df["patientunitstayid"].nunique())

(2520, 29)
2520

In [19]:
print(patient_df["patientunitstayid"].value_counts().max())

1